export const NEXT_PUBLIC_API_URL =
  process.env.NEXT_PUBLIC_API_URL ?? "INVALID NEXT_PUBLIC_API_URL";
export const NEXT_PUBLIC_BACKEND_API_URL =
  process.env.NEXT_PUBLIC_BACKEND_API_URL ?? "INVALID NEXT_PUBLIC_BACKEND_API_URL";
