// THIS FILE IS AUTO-GENERATED BY scripts/collect-locales.js
/* eslint-disable */
// Generated imports for component-local i18n JSON files

import app_de_1 from './../features/app/AppBar/locales/de.json';
import auth_de_2 from './../features/auth/ui/locales/de.json';
import group_de_3 from './../features/group/ui/locales/de.json';
import SidebarDrawer_de_4 from './../shared/ui/SidebarDrawer/locales/de.json';
import app_en_5 from './../features/app/AppBar/locales/en.json';
import auth_en_6 from './../features/auth/ui/locales/en.json';
import group_en_7 from './../features/group/ui/locales/en.json';
import SidebarDrawer_en_8 from './../shared/ui/SidebarDrawer/locales/en.json';

const app_de = app_de_1;
const auth_de = auth_de_2;
const group_de = group_de_3;
const SidebarDrawer_de = SidebarDrawer_de_4;
const app_en = app_en_5;
const auth_en = auth_en_6;
const group_en = group_en_7;
const SidebarDrawer_en = SidebarDrawer_en_8;

export const generatedI18n: Record<string, Record<string, any>> = {
  'de': {
    'app': app_de,
    'auth': auth_de,
    'group': group_de,
    'SidebarDrawer': SidebarDrawer_de,
  },
  'en': {
    'app': app_en,
    'auth': auth_en,
    'group': group_en,
    'SidebarDrawer': SidebarDrawer_en,
  },
};

export default generatedI18n;
export const generatedNS = [
  "app",
  "auth",
  "group",
  "SidebarDrawer"
];
