name: 'Setup Deployment'
description: 'Configure deployment environment and type'

inputs:
  deployment_type_override:
    description: 'Override deployment type (docker/traditional)'
    required: false
  deployment_type_default:
    description: 'Default deployment type from repository variables'
    required: false
    default: 'docker'
  environment:
    description: 'Target environment override'
    required: false
    default: 'auto'
  release_version:
    description: 'Version from release job (if available)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get current version
      id: get_version
      run: |
        VERSION=$(node -p "require('./frontend/package.json').version")
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "📦 Current version: ${VERSION}"
      shell: bash

    - name: Configure deployment
      id: config
      run: |
        echo "🔍 Debug: GitHub Ref: ${GITHUB_REF}"
        echo "🔍 Debug: deployment_type_override input: '${{ inputs.deployment_type_override }}'"
        echo "🔍 Debug: deployment_type_default input: '${{ inputs.deployment_type_default }}'"
        
        # Determine if this is a release tag push
        IS_RELEASE=false
        if [[ "${GITHUB_REF}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          IS_RELEASE=true
          ENVIRONMENT="production"
          echo "🏷️  Release tag detected: ${GITHUB_REF#refs/tags/}"
        else
          # Determine environment from branch or override
          if [ -n "${{ inputs.environment }}" ] && [ "${{ inputs.environment }}" != "auto" ]; then
            ENVIRONMENT="${{ inputs.environment }}"
          else
            case "${GITHUB_REF#refs/heads/}" in
              main)
                ENVIRONMENT="staging"
                echo "📌 Push to main branch → staging deployment"
                ;;
              develop)
                ENVIRONMENT="staging"
                echo "📌 Push to develop branch → staging deployment"
                ;;
              *)
                echo "⚠️  Unsupported branch: ${GITHUB_REF#refs/heads/}"
                echo "should_deploy=false" >> $GITHUB_OUTPUT
                exit 0
                ;;
            esac
          fi
        fi

        # Determine deployment type (workflow_dispatch override or repository variable or default)
        if [ -n "${{ inputs.deployment_type_override }}" ]; then
          DEPLOYMENT_TYPE="${{ inputs.deployment_type_override }}"
          echo "🔧 Using manual override: $DEPLOYMENT_TYPE"
        else
          DEPLOYMENT_TYPE="${{ inputs.deployment_type_default }}"
          echo "🔧 Using configured default: $DEPLOYMENT_TYPE"
        fi

        # Validate deployment type
        if [[ "$DEPLOYMENT_TYPE" != "docker" && "$DEPLOYMENT_TYPE" != "traditional" ]]; then
          echo "❌ Invalid deployment type: $DEPLOYMENT_TYPE"
          echo "should_deploy=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        # Generate image tag for docker deployments
        IMAGE_TAG=""
        if [[ "$DEPLOYMENT_TYPE" == "docker" ]]; then
          if [[ "$IS_RELEASE" == "true" ]]; then
            # Production release
            VERSION="${GITHUB_REF#refs/tags/v}"
            IMAGE_TAG="v${VERSION}"
          elif [[ "$ENVIRONMENT" == "production" ]]; then
            # Production (manual)
            IMAGE_TAG="latest"
          else
            # Staging
            COMMIT_SHORT=$(git rev-parse --short HEAD)
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            IMAGE_TAG="staging-${COMMIT_SHORT}-${TIMESTAMP}"
          fi
        fi

        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
        echo "deployment_type=$DEPLOYMENT_TYPE" >> $GITHUB_OUTPUT
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "should_deploy=true" >> $GITHUB_OUTPUT
        echo "is_release=$IS_RELEASE" >> $GITHUB_OUTPUT
        
        echo "🔍 Debug outputs:"
        echo "  - environment: $ENVIRONMENT"
        echo "  - deployment_type: $DEPLOYMENT_TYPE"
        echo "  - image_tag: $IMAGE_TAG"
        echo "  - should_deploy: true"
        echo "  - is_release: $IS_RELEASE"

        echo ""
        echo "🎯 Deployment Configuration:"
        echo "  Environment: $ENVIRONMENT"
        echo "  Type: $DEPLOYMENT_TYPE"
        echo "  Image Tag: $IMAGE_TAG"
        echo "  Is Release: $IS_RELEASE"
      shell: bash

outputs:
  environment:
    description: 'Target environment'
    value: ${{ steps.config.outputs.environment }}
  deployment_type:
    description: 'Deployment type'
    value: ${{ steps.config.outputs.deployment_type }}
  should_deploy:
    description: 'Whether deployment should proceed'
    value: ${{ steps.config.outputs.should_deploy }}
  image_tag:
    description: 'Docker image tag'
    value: ${{ steps.config.outputs.image_tag }}
  version:
    description: 'Application version'
    value: ${{ inputs.release_version || steps.get_version.outputs.version }}
  is_release:
    description: 'Whether this is a release deployment'
    value: ${{ steps.config.outputs.is_release }}